version: '3.8'

# Define services for the project
services:
  # Nginx service for handling web traffic
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx configuration
    networks:
      - cangrownet  # Use the cangrownet network
    env_file: env.  # Load environment variables from the 'env' file

  # First instance of WordPress
  wordpress1:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html  # Mount data volume for WordPress
    networks:
      - cangrownet  # Use the cangrownet network
    env_file: env.  # Load environment variables from the 'env' file

  # Second instance of WordPress
  wordpress2:
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html  # Mount data volume for WordPress
    networks:
      - cangrownet  # Use the cangrownet network
    env_file: env.  # Load environment variables from the 'env' file

  # Master MariaDB database
  mariadb-master:
    image: mariadb:latest
    volumes:
      - master-data:/var/lib/mysql  # Mount data volume for MariaDB
    networks:
      - cangrownet  # Use the cangrownet network
    env_file: env.  # Load environment variables from the 'env' file

  # Replica MariaDB database
  mariadb-replica:
    image: mariadb:latest
    volumes:
      - replica-data:/var/lib/mysql  # Mount data volume for MariaDB
    networks:
      - cangrownet  # Use the cangrownet network
    command: --replicate-do-db=mydb --server-id=2  # Set up replication parameters
    env_file: env.  # Load environment variables from the 'env' file

  # ProxySQL service for database load balancing
  proxysql:
    image: proxysql/proxysql
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf  # Mount ProxySQL configuration
    ports:
      - "6033:6033"  # Expose port 6033 for ProxySQL
    depends_on:
      - mariadb-master  # Depend on the master MariaDB instance
      - mariadb-replica  # Depend on the replica MariaDB instance
    networks:
      - cangrownet  # Use the cangrownet network
    env_file: env.  # Load environment variables from the 'env' file

# Define volumes for persistent data storage
volumes:
  wordpress_data:  # Volume for WordPress data
  master-data:  # Volume for master MariaDB data
  replica-data:  # Volume for replica MariaDB data

# Define network configuration
networks:
  cangrownet:  # Define a custom bridge network
    driver: bridge  # Use the bridge network driver
    ipam:
      driver: default  # Use the default IP address management driver
      config:
        - subnet: 172.28.0.0/28  # Define the IP subnet for the network
