name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build steps here if needed

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 185.240.151.74
          username: debian
          password: 2v1n3x6j7u
          script: |
           sudo cd /var/lib/docker/overlay2/6224b9db33212c98f0a8fa6ee142cd3bc5394e71b809ebd68e7403550137648d/diff/usr/src/wordpress/wp-content/themes
            git pull origin main
