name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy theme
        run: |
          cp -r /github/Cangrow-Project/twentytwentytwo   http://185.240.151.74/wp-admin/themes.php?theme=twentytwentytwo
