name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to WordPress Theme
        uses: appleboy/rsync-action@master
        with:
          args: -avz --delete ./wp-content/themes/twentytwentytwo debian@185.240.151.74:/var/lib/docker/overlay2/6224b9db33212c98f0a8fa6ee142cd3bc5394e71b809ebd68e7403550137648d/diff/usr/src/wordpress/wp-content/themes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
